<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.basarsy</groupId>
	<artifactId>skyline-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>skyline-parent</name>
	<description>Skyline Airline Management System - Microservices Aggregator</description>

	<modules>
		<module>skyline-common</module>
		<module>skyline-gateway</module>
		<module>skyline-auth</module>
		<module>skyline-fleet</module>
		<module>skyline-route</module>
		<module>skyline-schedule</module>
		<module>skyline-reservation</module>
		<module>skyline-checkin</module>
		<module>skyline-crew</module>
	</modules>

</project>
